name: Build App
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
          - platform: 'ubuntu-22.04'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build Tauri App
        run: npx tauri build